### PR TITLE
Phpunit 6

### PR DESCRIPTION
**Pull request by mario-naether**
For issue #34 .
Thats a compatibility layer for PHPUnit 6. I have tested with PhpUnit 6.2.4 .

### CODE REVIEW

**Comment by IchHabRecht** [comment]
HI Mario,

thank you for your pull request. Would you mind to tell me what the benefit of this patch is? IMHO if the testing framework should support PHPUnit 6.x it has to use that version as well (which then requires a new major version as that would be a breaking change).

Unfortunately I don't see any improvements in shipping class aliases for PHPUnit class names.

Thank you very much for your answer.

**Comment by mario-naether** [comment]
Hi Nicole,
the benfit of this patch is, this works with PHPUnit 4.8, 5.* and 6.*. Take a look at the trivis jobs for this pull-request!
I have copied the class alias stuff from codeception, thats works good.
You can also change the phpunit support to v6 (change to namespaces) and create a major version. 
This patch supports old versions, too.

Mario

**Comment by mario-naether** [comment]
@IchHabRecht 
PS: I found a  alternative TYPO3 Core Package for TYPO3 v8 and PHP 6.
https://github.com/TYPO3/testing-framework

**Comment by IchHabRecht** [comment]
Closed in favour of #57

**Pull request closed without merging**
