### PR TITLE
[FEATURE] Add compatibility to TYPO3 12.4

### PR DESCRIPTION
**Pull request by Kanti**

### CODE REVIEW

**Review by oliverklee — APPROVED** [review]

**Comment by Kanti** [comment]
travis is currently Blocked by this PR: https://github.com/Nimut/typo3-complete/pull/6

**Comment by simonschaufi** [comment]
@IchHabRecht are there any plans to make this testing framework finally compatible with v12? It would be great to be able to use it in my extensions!

**Comment by helhum** [comment]
@simonschaufi There won't be a v12 compatible version at all. It would be again a huge effort. Now that the typo3 testing framework is supporting multiple typo3 versions, it's recommended to switch to that for typo3 12 or higher

**Comment by simonschaufi** [comment]
ok. maybe this can be mentioned in the readme?

**Comment by helhum** [comment]
> ok. maybe this can be mentioned in the readme?

Yes. There is a ticket for that: #157

**Pull request closed without merging**
