### PR TITLE
[FEATURE] Copy ExtensionTestEnvironment from TYPO3 testing framework

### PR DESCRIPTION
**Pull request by simonschaufi**
This class is added as composer "script" in TYPO3 extensions:

```json
"scripts": {
     "post-autoload-dump": [
          "@prepare-extension-test-environment"
     ],
     "prepare-extension-test-structure": [
          "Nimut\\TestingFramework\\Composer\\ExtensionTestEnvironment::prepare"
     ]
},
```

### CODE REVIEW

**Comment by IchHabRecht** [comment]
Hi @simonschaufi,

Thank you for your pull request. I try to work on that in the next couple of days. First thoughts: I don't want the command to be run by default but just offer extensions to might use it. Secondly I think the paths need to be adjusted as the directory structure from nimut is slightly different to the typo3 ones. But I will check this again.

**Comment by simonschaufi** [comment]
The `post-autoload-dump` is not added by default. The extension developer has to do this manually. Yes, Nimut internally has different directory structure but this is not for Nimut but for the extension that needs to be tested and there the paths are always the same but let my confirm that myself again just to be 100% sure.

**Comment by IchHabRecht** [comment]
Hi @simonschaufi,

Sorry, I mixed up your pull request and the comment in this issue. But using __DIR__ is based on the nimut structure, not the extensions one.

**Comment by simonschaufi** [comment]
@IchHabRecht It was not my intention to give you so much work to refactor everything. Doesn't it make sense to stay close to the TYPO3 testing framework? Thank you so much for all the work you put into this :orange_heart:

**Comment by simonschaufi** [comment]
:tada: Thank you!

**Pull request merged**
