### PR TITLE
Update PHPUnit compatibility

### LINKED ISSUE #119: Add support for PHPUnit 8
Currently PHPUnit 6 || 7   are  supported, it would be good to also support the 8 release.
thanks :)

### PR DESCRIPTION
**Pull request by IchHabRecht**
Raise PHPUnit compatibility to versions 8.x and 9.x

Resolves: #119

### CODE REVIEW

**Comment by dkd-kaehm** [comment]
I rebased your branch and testet it within EXT:solr local and on travis.
It was the dependency for my tries on [paratest](https://github.com/paratestphp/paratest/) integration.

**Comment by helhum** [comment]
Here is my branch with rebased commits: https://github.com/helhum/TYPO3-testing-framework/tree/php8

**Comment by mbrodala** [comment]
@IchHabRecht @helhum how to proceed here? It looks like @helhum already did prepare the necessary updates ...

**Comment by IchHabRecht** [comment]
The problem should be solved in https://github.com/Nimut/testing-framework/commit/9e4f5df15a9f75277c1704a36dce452d2cec5edc

**Comment by mbrodala** [comment]
@IchHabRecht Thanks, I've successfully upgraded to PHPUnit 8.5 with this.

However with PHPUnit 9 an issues occurs because the the `Text_Template` class has been renamed to `SebastianBergmann\Template\Template`:

```
Error: Class 'Text_Template' not found
/.../vendor/nimut/testing-framework/src/TestingFramework/TestCase/AbstractFunctionalTestCase.php:473
```

This has been reported in https://github.com/Nimut/testing-framework/issues/144 already AFAIS.

(There's another one,  but this can be migrated locally as mentioned: `PHPUnit\Framework\TestCase::prophesize() is deprecated and will be removed in PHPUnit 10. Please use the trait provided by phpspec/prophecy-phpunit.`)

**Pull request closed without merging**
